# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
%pip install torch torchvision torchaudio pandas numpy matplotlib;


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
T = torch.rand(7, 7)
print(T)

tensor([[0.9758, 0.8094, 0.1026, 0.0738, 0.5578, 0.4645, 0.0632],
        [0.6668, 0.3093, 0.0761, 0.7808, 0.3286, 0.4536, 0.6224],
        [0.0690, 0.5879, 0.3589, 0.0617, 0.7877, 0.3525, 0.9619],
        [0.6587, 0.2028, 0.6830, 0.4056, 0.9843, 0.9336, 0.8763],
        [0.6346, 0.5783, 0.4600, 0.6930, 0.0594, 0.5635, 0.1763],
        [0.5495, 0.6461, 0.2528, 0.6535, 0.9437, 0.3242, 0.1339],
        [0.9289, 0.4451, 0.1888, 0.4852, 0.2940, 0.1944, 0.6508]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
T2 = torch.rand(1, 7)

# Perform matrix multiplication
TT2 = T @ T2.T
print(TT2)

tensor([[1.8360],
        [1.9636],
        [1.7323],
        [2.8527],
        [1.9783],
        [1.9980],
        [1.8394]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
T1 = torch.rand(7, 7)
T2 = torch.rand(1, 7)


# Matrix multiply tensors
T1T2 = T1 @ T2.T
print(T1T2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device = "mps" if torch.backends.mps.is_available() else device

# Create two random tensors on GPU
T1 = torch.rand(2, 3).to(device)
T2 = torch.rand(2, 3).to(device)

print(T1)
print(T2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='mps:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='mps:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
T1T2 = T1 @ T2.T
print(T1T2)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
max_T1T2 = T1T2.max()
print(max_T1T2)

# Find min
min_T1T2 = T1T2.min()
print(min_T1T2)

tensor(0.5617, device='mps:0')
tensor(0.3647, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
max_idx_T1T2 = T1T2.argmax()
print(max_idx_T1T2)


# Find arg min
min_idx_T1T2 = torch.argmin(T1T2)
print(min_idx_T1T2)

tensor(3, device='mps:0')
tensor(0, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)


# Create random tensor
T = torch.rand(1, 1, 1, 10)


# Remove single dimensions
T_squeezed = T.squeeze()


# Print out tensors and their shapes
print(T, T.shape)
print(T_squeezed, T_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
